name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  paramTag:
    description: 'param tag'
    required: true
outputs:
  timee: # id of output
    description: 'The time we greeted you'
  fullVersion:
    description: 'resolved param tag'
#env:
  #sshUserPrivateKey:  ${{ secrets.sshUserPrivateKey }}
  #ADITO_DESIGNER_REPO_URL_SSH: ${{ secrets.ADITO_DESIGNER_REPO_URL_SSH }}
  #MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
  #MAVEN_TOOLCHAINS: ${{ secrets.MAVEN_TOOLCHAINS }}
runs:
  using: 'node16'
  main: 'index.js'
