// gets added to designer-ci build.yml
// https://github.com/aditosoftware/adito-designer-ci/blob/main/.github/workflows/build.yml

# UITests on all plattforms in parallel
  unit_test:
    runs-on: ${{ matrix.os }}
    name: UI Tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      # Persist github actions
      - name: Github Action Cache
        uses: actions/cache@v2
        id: github-cache
        with:
          path: ./.github
          key: gh-build-${{ github.run_id }}-${{ github.run_number }}

      # Check if action exists
      - name: Check Action Exists
        id: check_action_exists
        uses: andstor/file-existence-action@v1
        with:
          files: ".github/workflows/uitest-action"

      # Execute Action
      - name: UI Tests
        if: steps.check_action_exists.outputs.files_exists == 'true'
        uses: ./.github/workflows/ui-action
        with:
          nexus_user: ${{ secrets.nexus_user }}
          nexus_password: ${{ secrets.nexus_password }}
