name: "Build Project"
description: "Executes a maven clean install"
inputs:
  nexus_user:
    description: 'Nexus Username'
    required: true
  nexus_password:
    description: 'Nexus Password'
    required: true

runs:
  using: "composite"
  steps:
    # Build vorbereiten
    - name: Prepare Maven Build
      uses: ./.github/workflows/prepare-action
      with:
        nexus_user: ${{ inputs.nexus_user }}
        nexus_password: ${{ inputs.nexus_password }}

    # Clean
    - name: Cleanup Maven Targets
      shell: bash
      run: mvn --batch-mode clean

    # Install, ohne Tests
    - name: Compile Project
      shell: bash
      run: mvn --batch-mode install -U -T 1C -DskipTests