name: "Prepare Maven Build"
description: "Prepares the maven build and includes caching of current artefacts (and m2)"
inputs:
  nexus_user:
    description: 'Nexus Username'
    required: true
  nexus_password:
    description: 'Nexus Password'
    required: true

runs:
  using: "composite"
  steps:
    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: 13
        distribution: 'adopt'

    - name: settings.xml
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        servers: >
          [{ 
            "id": "default", 
            "username": "${{ inputs.nexus_user }}", 
            "password": "${{ inputs.nexus_password }}"
          }, 
          {
            "id": "snapshots", 
            "username": "${{ inputs.nexus_user }}", 
            "password": "${{ inputs.nexus_password }}"
          }]
        repositories: >
          [{ 
            "id": "default", 
            "name": "default", 
            "url": "https://nexus.adito.cloud/repository/public/", 
            "releases": { "enabled": "true" } 
          }, 
          { 
            "id": "snapshots", 
            "name": "snapshots", 
            "url": "https://nexus.adito.cloud/repository/snapshots/", 
            "snapshots": { "enabled": "true", "updatePolicy": "always" } 
          }]
        plugin_repositories: >
          [{ 
             "id": "default", 
             "url": "https://nexus.adito.cloud/repository/public/", 
             "releases": { "enabled": "true" }, 
             "snapshots": { "enabled": "true", "updatePolicy": "always" } 
          }]



    - name: new settings.xml
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://nexus.adito.cloud/repository/releases/",
              "snapshots": {
                "enabled": "false",
                "updatePolicy": "always"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://nexus.adito.cloud/repository/snapshots/",
              "snapshots": {
                "updatePolicy": "always"
              }
            },
            {
              "id": "central",
              "url": "https://nexus.adito.cloud/repository/public",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "central",
              "url": "https://nexus.adito.cloud/repository/public",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "adito.m2",
              "username": "${{ inputs.nexus_user }}",
              "password": "${{ inputs.nexus_password }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "adito.m2",
              "mirrorOf": "*",
              "url": "https://nexus.adito.cloud/repository/public"
            }
          ]
        profiles: >
          [
            {
              "id": "adito.m2"
            }
          ]
        active_profiles: >
          [
            "adito.m2"
          ]
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    - name: 2.0 settings.xml
      uses: whelk-io/maven-settings-xml-action@v21
      with:
         mirrors: >
          [
            {
              "id": "adito.m2",
              "mirrorOf": "*",
              "url": "https://nexus.adito.cloud/repository/public"
            }
          ]
        profiles: >
          [
            {
              "id": "adito.m2",
              "properties": {
                "repository.releases": "https://nexus.adito.cloud/repository/releases/",
                "repository.snapshots": "https://nexus.adito.cloud/repository/snapshots/"
              }
            }
          ]
        active_profiles: >
          [
            "adito.m2"
          ]
        servers: >
          [
            {
              "id": "adito.m2",
              "username": "${{ inputs.nexus_user }}",
              "password": "${{ inputs.nexus_password }}"
            }
          ]
        
        repositories: >
          [
            {
              "id": "releases",
              "name": "releases",
              "url": "https://nexus.adito.cloud/repository/releases/",
              "snapshots": {
                "enabled": "false",
                "updatePolicy": "always"
              }
            },
            {
              "id": "snapshots",
              "name": "snapshots",
              "url": "https://nexus.adito.cloud/repository/snapshots/",
              "snapshots": {
                "updatePolicy": "always"
              }
            },
            {
              "id": "central",
              "url": "https://nexus.adito.cloud/repository/public",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true",
                "updatePolicy": "always"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "central",
              "url": "https://nexus.adito.cloud/repository/public",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
