name: execute-simplecalc
run-name: ${{ github.actor }} tried to execute simplecalc
on: workflow_dispatch

jobs:
  run-file:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      #- run: java -jar simplecalc.jar
      #  timeout-minutes: 2
      - run: calc/calc.exe
        timeout-minutes: 2
