name: execute-simplecalc
run-name: ${{ github.actor }} tried to execute simplecalc
on: workflow_dispatch

jobs:
  run-file:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: java -jar simplecalc.jar
