on:
  workflow_dispatch:
    inputs:
      paramTag:
        description: 'param tag'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest      # matrix os later to run on all os
    name: build working designer
    steps:
        
      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: 'adopt'
        
      - name: checkout ao repo
        uses: actions/checkout@v3
        #with:
        
      - name: move ao files to ao folder    # rename test1 to ao
        shell: bash
        run: |
          echo move ao files to ao folder:       
          mv /home/runner/work/test1/test1 /home/runner/work/test1/ao
          echo create designer folder:
          mkdir /home/runner/work/test1/test1
          echo JAVA_HOME:
          echo $JAVA_HOME
          echo HOME:
          echo $HOME
        
      - name: checkout designer    # to /home/runner/work/test1/test1 || lfs argument default false?
        uses: actions/checkout@v3
        
      - name: javascript action step
        id: hello
        uses: 2Akuma2/test1/js@main
        with:
          who-to-greet: 'Mona the Octocat'
          paramTag: ${{ inputs.paramTag }}
        
        
      - name: move ao files to ao folder    # rename test1 to ao
        shell: bash
        run: |
          echo print out aditoVersion.properties
          cd $HOME/work/test1/ao/library/core/target/classes/de/adito/aditoweb/core/version
          cat aditoVersion.properties
          echo print out aditoDesigner.conf
          cd $HOME/work/test1/ao/addendum/assemblydesigner/buildresources
          cat ADITOdesigner.conf
        
      # Use the output from the `js action` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.timee }}"
        
      - name: Get resolved param tag
        run: echo "The resolved param tag is ${{ steps.hello.outputs.fullVersion }}"
        
      - name: Get java version in main.yml
        run: java -version
