name: qfs-run
run-name: ${{ github.actor }} tried to run qfs demo carconfig_de.qft
on: workflow_dispatch
jobs:
  run-file:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull qualityfirstsoftware/qftest-interactive
      - run: docker run qualityfirstsoftware/qftest-interactive -batch -nomessagewindow -verbose errors,all /qftest/qftest-container/demo/carconfig/carconfig_en.qft

