name: qfs-run
run-name: ${{ github.actor }} tried to run qfs demo carconfig_de.qft
on: workflow_dispatch
jobs:
  run-file:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: QF-Test/qftest-6.0.3/bin/qftestc.exe -batch -run QF-Test/qftest-6.0.3/demo/carconfig/carconfig_de.qft
        timeout-minutes: 5

