on:
  workflow_dispatch:


jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    name: test it!
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    
    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: 13
        distribution: 'adopt'

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      uses: ./.github/workflows/prepare-action
      with:
        nexus_user: ABCD
        nexus_password: ABCD1234
        
    - name: print settings.xml (win)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Get-Content -Path ~\.m2\settings.xml;
        Get-Content -Path ~\.m2\settingss.xml;
        # Get-Content -Path ~\.m2\settingsss.xml
      
    - name: print settings.xml (lin)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        cat ~/.m2/settingss.xml
        # cat ~/.m2/settingsss.xml
    
    - name: print settings.xml (mac)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        cat ~/.m2/settingss.xml
        # cat ~/.m2/settingsss.xml
        
