on:
  workflow_dispatch:
    inputs:
      nexus_user:
        description: 'Nexus Username'
        required: true
      nexus_password:
        description: 'Nexus Password'
        required: true


jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test it!
    steps:
    
    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: 13
        distribution: 'adopt'

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      uses: ./.github/workflows/prepare-action
      with:
        nexus_user: ABCD
        nexus_password: ABCD1234
        
    - name: print settings.xml
      shell: bash
      run: cat ~/.m2/settings.xml
        
