
on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: windows-latest                    #${{ matrix.os }}
    name: build working designer
    #strategy:
      #fail-fast: false
      #matrix:
      #  include:
      #    - os: macos-latest
      #    - os: ubuntu-latest
      #    - os: windows-latest
    steps:
    
    - name: checkout ao repo
      uses: actions/checkout@v3
    
    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: 13
        distribution: 'adopt'
    
    
    
    
    
#    - name: win
#      if: runner.os == 'Windows'
#      shell: bash
#      run:  |
#        echo ${{ github.workspace }}
#        sed -r -i 's/\${installer:adito.installer.scaleui}/${{ env.scaleuiwin }}/g' QF-Test/ADITOdesigner.conf
#        sed -r -i 's/\${adito.complete.final.version}/${{ env.fullVersion }}/g' QF-Test/ADITOdesigner.conf
#        sed -r -i 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
#        sed -r -i 's!\${installer:adito.installer.basepath}/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
#        sed -r -i 's!\${installer:adito.installer.basepath}!${{ github.workspace }}!g' QF-Test/ADITOdesigner.conf
#        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
#        cat application/designer/target/aditodesigner/etc/ADITOdesigner.conf
#      env:
#        scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
#        fullVersion: '1234.5.6.7'
        
    
    - name: win
      if: runner.os == 'Windows'
      shell: bash
      run:  |
        echo ${{ github.workspace }}
        sed -r -i 's/"^${installer:adito.installer.scaleui}"/"${{ env.scaleuiwin }}"/g' QF-Test/ADITOdesigner.conf # > QF-Test/ADITOdesigner.conf
        cat QF-Test/ADITOdesigner.conf
      env:
        scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
        fullVersion: '1234.5.6.7'
    
    
    
    
    - name: win
      if: runner.os == 'Windows'
      shell: bash
      run:  |
        sed -r -i 's/$\{adito.complete.final.version}/${{ env.fullVersion }}/g' QF-Test/ADITOdesigner.conf
        sed -r -i 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
        
      env:
        scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
        fullVersion: '1234.5.6.7'
    
    
    - name: win
      if: runner.os == 'Windows'
      shell: bash
      run:  |
        sed -r -i 's!$\{installer:adito.installer.basepath}/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
        sed -r -i 's!$\{installer:adito.installer.basepath}!${{ github.workspace }}!g' QF-Test/ADITOdesigner.conf
        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
        cat application/designer/target/aditodesigner/etc/ADITOdesigner.conf
      env:
        scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
        fullVersion: '1234.5.6.7'
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    - name: lin
      if: runner.os == 'Linux'
      shell: bash
      run:  |
        sed -i 's/\${installer:adito.installer.scaleui}/${{ env.scaleuilin }}/g' QF-Test/ADITOdesigner.conf
        sed -i 's/\${adito.complete.final.version}/${{ env.fullVersion }}/g' QF-Test/ADITOdesigner.conf
        sed -i 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
        sed -i 's!\${installer:adito.installer.basepath}/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
        sed -i 's!\${installer:adito.installer.basepath}!${{ github.workspace }}!g' QF-Test/ADITOdesigner.conf
        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
        cat application/designer/target/aditodesigner/etc/ADITOdesigner.conf
      env:
        scaleuilin: ''
        fullVersion: '1234.5.6.7'
        
    - name: mac
      if: runner.os == 'macOS'
      shell: bash
      run:  |
        sed -i '' 's/\${installer:adito.installer.scaleui}/${{ env.scaleuimac }}/g' QF-Test/ADITOdesigner.conf
        sed -i '' 's/\${adito.complete.final.version}/${{ env.fullVersion }}/g' QF-Test/ADITOdesigner.conf
        sed -i '' 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
        sed -i '' 's!\${installer:adito.installer.basepath}/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
        sed -i '' 's!\${installer:adito.installer.basepath}!${{ github.workspace }}!g' QF-Test/ADITOdesigner.conf
        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
        cat application/designer/target/aditodesigner/etc/ADITOdesigner.conf
      env:
        scaleuimac: ''
        fullVersion: '1234.5.6.7'
      
      
      
