
on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    name: build working designer
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    
    - name: checkout ao repo
      uses: actions/checkout@v3
    
    - name: change scaleui (windows)
      if: runner.os == 'Windows'
      shell: bash
      run: sed -i 's/\${installer:adito.installer.scaleui}/$scaleuiwin/g' QF-Test/ADITOdesigner.conf
      env:
        scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
      
    - name: change scaleui (linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sed -i 's/\${installer:adito.installer.scaleui}/$scaleuilin/g' QF-Test/ADITOdesigner.conf
      env:
        scaleuilin: ''
      
    - name: change scaleui (macos)
      if: runner.os == 'macOS'
      shell: bash
      run: sed -i 's/\${installer:adito.installer.scaleui}/$scaleuimac/g' QF-Test/ADITOdesigner.conf
      env:
        scaleuimac: ''
    
    
    - name: remaining prep
      shell: bash
      run:  |
        sed -i 's/\${adito.complete.final.version}/$fullVersion/g' QF-Test/ADITOdesigner.conf
        sed -i 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
        sed -i 's!\${installer:adito.installer.basepath}/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
        sed -i 's/\${installer:adito.installer.basepath}/${{ github.workspace }}/g' QF-Test/ADITOdesigner.conf
        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
        cat application/designer/target/aditodesigner/etc/ADITOdesigner.conf
      env:
        fullVersion: '1234.5.6.7'
